### ISSUE TITLE
Jessica can't create a c9 account

### ISSUE THREAD

**Issue by chrisortman** [chrisortman/CIS-121#2]
Jessica
Katie

**Comment by chrisortman** [comment]
As is often the case we are not the only people with this problem

https://community.c9.io/t/credit-card-required-for-free-account/7434/43

**Comment by kpgardner** [comment]
I tried it from home and it worked.
-Katie

**Comment by bruno16mch** [comment]
c9 is working for me as well.
-Bruno

**Comment by BConquest** [comment]
c9 is working for me
-Bryant

**Comment by chrisortman** [comment]
Good to hear it's working.
It looks like there was quite a bit of backlash over the credit card change (which was very recent) so cloud9 created an education plan. I'm trying to see if kirkwood will pay for this, if not I will so then I should be able to create accounts for people.
