### ISSUE TITLE
Print LCD Numbers

### ISSUE THREAD

**Issue by chrisortman** [chrisortman/CIS-121#48]
This is a problem taken from a bunch of quizzes used in [ruby](https://ruby-lang.org)

LCD Numbers (14)
This week's quiz is to write a program that displays LCD style numbers at adjustable sizes.

The digits to be displayed will be passed as an argument to the program. Size should be controlled with the command-line option -s follow up by a positive integer. The default value for -s is 2.

For example, if your program is called with:

> lcd.py 012345

The correct display is:

```
 --        --   --        -- 
|  |    |    |    | |  | |   
|  |    |    |    | |  | |   
           --   --   --   -- 
|  |    | |       |    |    |
|  |    | |       |    |    |
 --        --   --        -- 
```

And for:

> lcd.rb -s 1 6789

Your program should print:

```
 -   -   -   - 
|     | | | | |
 -       -   - 
| |   | | |   |
 -       -   - 
```

Note the single column of space between digits in both examples. For other values of -s, simply lengthen the - and | bars.

There are answers out there, a lot of them are done in ruby but I'm sure it has been solved in most languages.

If you are stuck, try thinking what the smallest piece you could implement is to feel some success. Then do that and build.

 [source](http://rubyquiz.com/quiz14.html)

**Comment by BConquest** [comment]
I almost have it working but how would I get the numbers to print out beside each other?

**Comment by chrisortman** [comment]
that's the tricky part :)
since its a terminal you can only print line by line
