### ISSUE TITLE
Cool PIP Modules

### ISSUE THREAD

**Issue by chrisortman** [chrisortman/CIS-121#65]
Put your links here in comments

**Comment by bruno16mch** [comment]
https://pypi.python.org/pypi/fallingsky/

**Comment by kpgardner** [comment]
https://pypi.python.org/pypi/pysteroids/

**Comment by Andrew-Rompot** [comment]
https://pypi.python.org/pypi/musichaos/

**Comment by jessicatse** [comment]
https://pypi.python.org/pypi/housecanary/0.5.2

**Comment by k0459866** [comment]
https://pypi.python.org/pypi/bot-dahi/0.1.13

**Comment by jnemmers** [comment]
https://github.com/svisser/crossword

**Comment by Parker17** [comment]
https://github.com/pahaz/sshtunnel

**Comment by AndrewMurley** [comment]
https://pypi.python.org/pypi/mtg-deck-editor/
https://pypi.python.org/pypi/mtg-ssm/
https://pypi.python.org/pypi/mtg/

**Comment by FlippantSol** [comment]
https://pypi.python.org/pypi/vai/
https://pypi.python.org/pypi/PythonToolkit/

**Comment by BConquest** [comment]
https://pypi.python.org/pypi/pyspacewar/

**Comment by ZachFord17** [comment]
https://pypi.python.org/pypi/purepng/0.2.0

**Comment by AndrewMurley** [comment]
https://pypi.python.org/pypi/mtg-deck-editor/
