### ISSUE TITLE
Audio in/from Python

### ISSUE THREAD

**Issue by k0459866** [chrisortman/CIS-121#67]
I'm having difficulties getting sound to play in python, or get it to redirect me to a webpage with the audio in it. I've looked online for some help, but I'm not really understanding the examples that they use. My project is meant to upload an audio file from a webpage (or from a user) and play it with a variable tempo, set by the user. I'm a little confused about this and I'm not really sure where I should start.

-Logan

**Comment by chrisortman** [comment]
I think we talked about this in class, just in case here are a couple of links to get you going

https://developer.mozilla.org/en-US/docs/Web/Guide/HTML/Using_HTML5_audio_and_video

https://developer.mozilla.org/en-US/Apps/Fundamentals/Audio_and_video_delivery/WebAudio_playbackRate_explained

These links cover the HTML part, so they tell us what text we need to generate, 

https://docs.djangoproject.com/en/1.9/ref/templates/language/

explains a little bit about how we'll generate it
