### ISSUE TITLE
Mid-Term Project: Audio Playing and Variable Playback Speeds

### ISSUE THREAD

**Issue by k0459866** [chrisortman/CIS-121#73]
I'm having troubles with getting the HTML file to work along with the Django ones. You helped me on Friday with it and you said you'd get back to me over the weekend.

-Logan Walsh

**Comment by chrisortman** [comment]
I got it to work...the reason it wasn't working for us on Friday is that we

1) Have to put the static folder inside a _module_
2) Didn't have a module to put it into
3) Didn't add our module to the settings.py

So you'll have to 

```
python manage.py startapp player
```

I'm just taking a stab at the player name

Then add 'player.apps.PlayerConfig' to the INSTALLED_APPS in settings.py

Then add html and audio files to `player/static/player/` and they should then be accessible from /static

Working through the _polls_ tutorial on the django site is very helpful. I would suggest doing it  in your app. You only need to get to lesson 5 before it starts talking about static files and then you have something to compare against.

https://docs.djangoproject.com/en/1.9/intro/tutorial01/
